#!/usr/bin/env bash
set -euo pipefail

# Generates a robust, repo-aware README.md for this LookML -> dbt -> Sigma project.
# Usage:
#   bash make_readme.sh [repo_root] [output_file]
# Example:
#   bash make_readme.sh . README.md

REPO_ROOT="${1:-.}"
OUTPUT_FILE="${2:-README.md}"

cd "$REPO_ROOT"

PROJECT_BASENAME="$(basename "$PWD")"
PROJECT_BASE_CLEAN="${PROJECT_BASENAME%-main}"
TIMESTAMP_UTC="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

trim() {
  awk '{$1=$1; print}' <<<"${1:-}"
}

title_case() {
  local input="${1//[_-]/ }"
  awk '
    {
      for (i = 1; i <= NF; i++) {
        $i = toupper(substr($i,1,1)) tolower(substr($i,2))
      }
      print
    }
  ' <<<"$input"
}

md_escape() {
  local s="${1:-}"
  s="${s//|/\\|}"
  printf '%s' "$s"
}

append_line() {
  printf '%s\n' "$1" >> "$TMP_FILE"
}

append_blank() {
  printf '\n' >> "$TMP_FILE"
}

append_section() {
  append_blank
  append_line "$1"
  append_blank
}

backup_existing_readme() {
  if [[ -f "$OUTPUT_FILE" ]]; then
    local backup
    backup="${OUTPUT_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$OUTPUT_FILE" "$backup"
    echo "Backed up existing $OUTPUT_FILE to $backup"
  fi
}

get_workflow_file() {
  find .github/workflows -maxdepth 1 -type f \( -name '*.yml' -o -name '*.yaml' \) 2>/dev/null | sort | head -n 1 || true
}

get_workflow_name() {
  local wf="$1"
  [[ -f "$wf" ]] || return 0
  grep -E '^name:' "$wf" | head -n 1 | sed 's/^name:[[:space:]]*//' || true
}

get_workflow_python_version() {
  local wf="$1"
  [[ -f "$wf" ]] || return 0
  grep -E 'python-version:' "$wf" | head -n 1 | awk -F ':' '{print $2}' | tr -d "'\"[:space:]" || true
}

get_workflow_node_version() {
  local wf="$1"
  [[ -f "$wf" ]] || return 0
  grep -E 'node-version:' "$wf" | head -n 1 | awk -F ':' '{print $2}' | tr -d "'\"[:space:]" || true
}

collect_requirements() {
  [[ -f requirements.txt ]] || return 0
  grep -Ev '^[[:space:]]*($|#)' requirements.txt || true
}

collect_lookml_model_dirs() {
  [[ -d lookml ]] || return 0
  find lookml -mindepth 1 -maxdepth 1 -type d | sort || true
}

count_files() {
  local dir="$1"
  local pattern="$2"
  [[ -d "$dir" ]] || { echo 0; return 0; }
  find "$dir" -type f -name "$pattern" | wc -l | tr -d ' '
}

collect_sql_tables() {
  [[ -d lookml ]] || return 0
  grep -RhoE 'sql_table_name:[[:space:]]*[^;]+' lookml 2>/dev/null \
    | sed -E 's/sql_table_name:[[:space:]]*//' \
    | sed 's/[[:space:]]*$//' \
    | sort -u || true
}

collect_report_warnings() {
  [[ -d out ]] || return 0
  python3 - <<'PY'
import glob, json
seen = set()
for path in sorted(glob.glob('out/*_report.json')):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        for item in data.get('warnings', []):
            if item and item not in seen:
                seen.add(item)
                print(item)
    except Exception:
        pass
PY
}

collect_join_mappings() {
  [[ -d out ]] || return 0
  python3 - <<'PY'
import glob, json
seen = set()
for path in sorted(glob.glob('out/*_report.json')):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        for item in data.get('joins_mapped', []):
            if item and item not in seen:
                seen.add(item)
                print(item)
    except Exception:
        pass
PY
}

license_detected() {
  find . -maxdepth 1 -type f \( -iname 'LICENSE' -o -iname 'LICENSE.txt' -o -iname 'LICENSE.md' \) | head -n 1 || true
}

REPO_TITLE="$(title_case "$PROJECT_BASE_CLEAN")"
WORKFLOW_FILE="$(get_workflow_file)"
WORKFLOW_NAME="$(trim "$(get_workflow_name "$WORKFLOW_FILE")")"
PYTHON_VERSION="$(trim "$(get_workflow_python_version "$WORKFLOW_FILE")")"
NODE_VERSION="$(trim "$(get_workflow_node_version "$WORKFLOW_FILE")")"
LICENSE_FILE="$(license_detected)"

backup_existing_readme

append_line "# $REPO_TITLE"
append_blank
append_line "This repository contains an end-to-end pipeline for converting LookML assets into Sigma-ready model artifacts. It includes sample LookML sources, helper patching scripts, generated manifests and reports, and a GitHub Actions workflow that runs the conversion pipeline."
append_blank
append_line "> Generated by \`$(basename "$0")\` on $TIMESTAMP_UTC."

append_section "## What this repo does"
append_line "At a high level, this project is designed to:"
append_blank
append_line "1. Store or generate LookML models and views under \`lookml/\`."
append_line "2. Convert LookML into dbt semantic model YAML using \`dbtc convert-lookml\`."
append_line "3. Patch relationships and entities with \`tools/patch_semantic_models.py\`."
append_line "4. Generate a semantic manifest with \`tools/generate_semantic_manifest.py\`."
append_line "5. Translate the semantic layer into Sigma-ready YAML through Sigma's converter."
append_line "6. Persist generated artifacts under \`out/\` and \`sigma_model/\`."

append_section "## Repository layout"
append_line '```text'
append_line '.'
for path in \
  .github \
  .github/workflows \
  create_lookml.sh \
  make_readme.sh \
  setup.sh \
  tools \
  lookml \
  out \
  sigma_model \
  requirements.txt; do
  if [[ -e "$path" ]]; then
    append_line "├── $path"
  fi
done
append_line '```'
append_blank
append_line "Key files:"
append_blank
append_line "- \`setup.sh\` — bootstraps directories, writes helper files, and runs LookML/README generation scripts."
append_line "- \`create_lookml.sh\` — creates the sample LookML project and view files."
append_line "- \`make_readme.sh\` — generates the README for the repository."
append_line "- \`tools/patch_semantic_models.py\` — patches converted semantic models using relationships inferred from LookML joins."
append_line "- \`tools/generate_semantic_manifest.py\` — builds the semantic manifest consumed by the Sigma conversion step."
if [[ -n "$WORKFLOW_FILE" ]]; then
  append_line "- \`$WORKFLOW_FILE\` — automates conversion on push and manual dispatch."
fi

append_section "## Current project contents"
if [[ -d lookml ]]; then
  append_line "Detected LookML model directories:"
  append_blank
  while IFS= read -r model_dir; do
    [[ -z "$model_dir" ]] && continue
    model_name="$(basename "$model_dir")"
    view_count="$(count_files "$model_dir" '*.view.lkml')"
    model_count="$(count_files "$model_dir" '*.model.lkml')"
    sigma_count="$(count_files "sigma_model/$model_name" '*.yml')"
    manifest_present="no"
    report_present="no"
    [[ -f "out/${model_name}_manifest.json" ]] && manifest_present="yes"
    [[ -f "out/${model_name}_report.json" ]] && report_present="yes"

    append_line "- **$model_name**"
    append_line "  - LookML model files: $model_count"
    append_line "  - LookML view files: $view_count"
    append_line "  - Generated Sigma YAML files: $sigma_count"
    append_line "  - Manifest present: $manifest_present"
    append_line "  - Report present: $report_present"
  done < <(collect_lookml_model_dirs)
else
  append_line "No \`lookml/\` directory was detected."
fi

SQL_TABLES="$(collect_sql_tables || true)"
if [[ -n "$SQL_TABLES" ]]; then
  append_blank
  append_line "Warehouse tables referenced by the current LookML views:"
  append_blank
  while IFS= read -r table_name; do
    [[ -z "$table_name" ]] && continue
    append_line "- \`$(md_escape "$table_name")\`"
  done <<< "$SQL_TABLES"
fi

append_section "## Prerequisites"
append_line "You will generally need the following to run this project locally:"
append_blank
append_line "- Bash"
append_line "- Python${PYTHON_VERSION:+ $PYTHON_VERSION or compatible}"
append_line "- pip"
append_line "- Node.js${NODE_VERSION:+ $NODE_VERSION}"
append_line "- Git"
append_line "- Access to the target Sigma environment and warehouse connection"
append_blank
append_line "The GitHub Actions workflow installs dependencies from \`requirements.txt\` and clones Sigma's converter during execution."

REQS="$(collect_requirements || true)"
if [[ -n "$REQS" ]]; then
  append_blank
  append_line "Python dependencies currently declared in this repo:"
  append_blank
  while IFS= read -r dep; do
    [[ -z "$dep" ]] && continue
    append_line "- \`$(md_escape "$dep")\`"
  done <<< "$REQS"
fi

append_section "## Setup"
append_line "A typical local setup flow looks like this:"
append_blank
append_line '```bash'
append_line 'git clone <your-repo-url>'
append_line "cd $PROJECT_BASENAME"
append_line 'bash setup.sh'
append_line '# Review and update .env before running the pipeline for real'
append_line '```'
append_blank
append_line "After running \`setup.sh\`, review \`.env\` carefully and replace placeholder values with real configuration before using the pipeline in CI/CD or against a live Sigma environment."

append_section "## Configuration"
append_line "The project expects a \`.env\` file with runtime configuration. Do **not** commit real secrets."
append_blank
append_line '| Variable | Purpose |'
append_line '|---|---|'
append_line '| `LOOKML_DIR` | Root directory containing LookML model subdirectories. |'
append_line '| `MANIFEST_DATABASE` | Warehouse database name used in the semantic manifest. |'
append_line '| `MANIFEST_SCHEMA` | Warehouse schema name used in the semantic manifest. |'
append_line '| `MANIFEST_TABLE_PREFIX` | Optional prefix applied to relation names during manifest generation. |'
append_line '| `MANIFEST_TABLE_SUFFIX` | Optional suffix applied to relation names during manifest generation. |'
append_line '| `API_URL` | Sigma API base URL. |'
append_line '| `SIGMA_DOMAIN` | Sigma domain for the target organization. |'
append_line '| `API_CLIENT_ID` | Sigma API client ID. |'
append_line '| `API_SECRET` | Sigma API secret. Keep this secret. |'
append_line '| `CONNECTION_ID` | Sigma warehouse connection ID used by generated artifacts. |'
append_line '| `SIGMA_FOLDER_ID` | Target Sigma folder ID. |'
append_line '| `MODE` | Execution mode for the pipeline. |'
append_line '| `USER_FRIENDLY_COLUMN_NAMES` | Controls naming style in generated outputs. |'
append_line '| `TEST_FLAG` | Indicates test-oriented behavior. |'
append_line '| `FROM_CI_CD` | Indicates whether the pipeline is running in CI/CD. |'

append_section "## How the workflow runs"
if [[ -n "$WORKFLOW_NAME" ]]; then
  append_line "Workflow detected: **$(md_escape "$WORKFLOW_NAME")**"
  append_blank
fi
append_line "The repository includes a GitHub Actions workflow that:"
append_blank
append_line "1. Checks out the repository."
append_line "2. Installs Python and Node dependencies."
append_line "3. Clones Sigma's \`dbt_semantics_to_sigma\` converter."
append_line "4. Iterates through each immediate subdirectory inside \`LOOKML_DIR\`."
append_line "5. Converts each LookML subdirectory into semantic models."
append_line "6. Patches semantic relationships and writes a migration report."
append_line "7. Generates a manifest file per model directory."
append_line "8. Produces Sigma YAML outputs under \`sigma_model/<model_name>/\`."
append_line "9. Commits generated artifacts back to the repository when changes exist."
append_blank
append_line "To trigger the hosted pipeline, push to \`main\` or run the workflow manually from GitHub Actions if \`workflow_dispatch\` is enabled."

append_section "## Running the pipeline locally"
append_line "This repo is primarily wired for GitHub Actions, but a local workflow can still follow the same broad sequence:"
append_blank
append_line '```bash'
append_line 'python -m pip install -r requirements.txt'
append_line 'bash create_lookml.sh'
append_line '# export variables from .env as needed'
append_line '# run dbtc convert-lookml inside each lookml/<model_dir>'
append_line 'python tools/patch_semantic_models.py <lookml_dir> <semantic_models_dir> <report_file>'
append_line 'python tools/generate_semantic_manifest.py <semantic_models_dir> <manifest_file>'
append_line '```'
append_blank
append_line "The Sigma conversion step relies on the separate converter cloned during the GitHub Actions run."

append_section "## Generated artifacts"
append_line "When the pipeline succeeds, you should expect outputs in these locations:"
append_blank
append_line "- \`out/*_manifest.json\` — semantic manifest files used by the Sigma conversion step."
append_line "- \`out/*_report.json\` — relationship patching and audit reports."
append_line "- \`sigma_model/<model_name>/*.yml\` — Sigma-ready model YAML files."

if [[ -d out || -d sigma_model ]]; then
  append_blank
  append_line "Currently detected generated files:"
  append_blank
  [[ -d out ]] && find out -maxdepth 1 -type f | sed 's#^#- `#; s#$#`#' | sort >> "$TMP_FILE" || true
  [[ -d sigma_model ]] && find sigma_model -maxdepth 2 -type f | sed 's#^#- `#; s#$#`#' | sort >> "$TMP_FILE" || true
fi

append_section "## Current caveats and observations"
WARNINGS="$(collect_report_warnings || true)"
JOIN_MAPPINGS="$(collect_join_mappings || true)"

if [[ -n "$WARNINGS" ]]; then
  append_line "The current generated reports include the following notable warnings:"
  append_blank
  while IFS= read -r warning; do
    [[ -z "$warning" ]] && continue
    append_line "- $(md_escape "$warning")"
  done <<< "$WARNINGS"
else
  append_line "No warnings were detected in the current report files."
fi

if [[ -n "$JOIN_MAPPINGS" ]]; then
  append_blank
  append_line "Relationship mappings currently inferred by the patching step:"
  append_blank
  while IFS= read -r mapping; do
    [[ -z "$mapping" ]] && continue
    append_line "- $(md_escape "$mapping")"
  done <<< "$JOIN_MAPPINGS"
fi

append_blank
append_line "Given the current sample contents, the most important thing to validate before production use is relationship accuracy. A \`many_to_many\` join can lead to fan-out issues, incorrect metrics, or poor downstream semantic behavior if it does not reflect the true grain of the data."

append_section "## Recommended next improvements"
append_line "Before using this pipeline beyond a demo or proof of concept, consider the following:"
append_blank
append_line "- Replace placeholder values in \`.env\` with real, environment-specific configuration."
append_line "- Add validation tests for join relationships and primary keys."
append_line "- Add a real local runner script if developers will execute the full pipeline outside GitHub Actions."
append_line "- Add CI checks for malformed LookML, missing semantic models, and empty generated outputs."
append_line "- Add a license file and contribution guidelines if this repo will be shared broadly."

append_section "## Contributing"
append_line "Contributions are welcome. When making changes, update the LookML sources, rerun generation, and review both \`out/\` reports and \`sigma_model/\` outputs before pushing."

append_section "## License"
if [[ -n "$LICENSE_FILE" ]]; then
  append_line "This repository includes a license file at \`$LICENSE_FILE\`."
else
  append_line "No license file was detected in the repository root. Add one before distributing this project externally."
fi

mv "$TMP_FILE" "$OUTPUT_FILE"
trap - EXIT

echo "README generated at $OUTPUT_FILE"
