#!/usr/bin/env bash
set -euo pipefail

# Generates a robust, repo-aware README.md for this LookML -> dbt -> Sigma project.
# Usage:
#   bash make_readme.sh [repo_root] [output_file]
# Example:
#   bash make_readme.sh . README.md

REPO_ROOT="${1:-.}"
OUTPUT_FILE="${2:-README.md}"

cd "$REPO_ROOT"

PROJECT_BASENAME="$(basename "$PWD")"
PROJECT_BASE_CLEAN="${PROJECT_BASENAME%-main}"
TIMESTAMP_UTC="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

trim() {
  awk '{$1=$1; print}' <<<"${1:-}"
}

title_case() {
  local input="${1//[_-]/ }"
  awk '
    {
      for (i = 1; i <= NF; i++) {
        $i = toupper(substr($i,1,1)) tolower(substr($i,2))
      }
      print
    }
  ' <<<"$input"
}

md_escape() {
  local s="${1:-}"
  s="${s//|/\\|}"
  printf '%s' "$s"
}

append_line() {
  printf '%s\n' "$1" >> "$TMP_FILE"
}

append_blank() {
  printf '\n' >> "$TMP_FILE"
}

append_section() {
  append_blank
  append_line "$1"
  append_blank
}

backup_existing_readme() {
  if [[ -f "$OUTPUT_FILE" ]]; then
    local backup
    backup="${OUTPUT_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$OUTPUT_FILE" "$backup"
    echo "Backed up existing $OUTPUT_FILE to $backup"
  fi
}

get_workflow_file() {
  find .github/workflows -maxdepth 1 -type f \( -name '*.yml' -o -name '*.yaml' \) 2>/dev/null | sort | head -n 1 || true
}

get_workflow_name() {
  local wf="$1"
  [[ -f "$wf" ]] || return 0
  grep -E '^name:' "$wf" | head -n 1 | sed 's/^name:[[:space:]]*//' || true
}

get_workflow_python_version() {
  local wf="$1"
  [[ -f "$wf" ]] || return 0
  grep -E 'python-version:' "$wf" | head -n 1 | awk -F ':' '{print $2}' | tr -d "'\"[:space:]" || true
}

get_workflow_node_version() {
  local wf="$1"
  [[ -f "$wf" ]] || return 0
  grep -E 'node-version:' "$wf" | head -n 1 | awk -F ':' '{print $2}' | tr -d "'\"[:space:]" || true
}

collect_requirements() {
  [[ -f requirements.txt ]] || return 0
  grep -Ev '^[[:space:]]*($|#)' requirements.txt || true
}

# List LookML project dirs: looker_files/ first (canonical), then lookml/. One name per dir (no duplicates).
collect_lookml_model_dirs() {
  local seen=""
  if [[ -d looker_files ]]; then
    while IFS= read -r d; do
      [[ -z "$d" ]] && continue
      local name="$(basename "$d")"
      echo "$d"
    done < <(find looker_files -mindepth 1 -maxdepth 1 -type d | sort)
  fi
  if [[ -d lookml ]]; then
    while IFS= read -r d; do
      [[ -z "$d" ]] && continue
      local name="$(basename "$d")"
      # Skip if we already listed this name from looker_files
      if [[ -d looker_files ]]; then
        [[ -d "looker_files/$name" ]] && continue
      fi
      echo "$d"
    done < <(find lookml -mindepth 1 -maxdepth 1 -type d | sort)
  fi
}

count_files() {
  local dir="$1"
  local pattern="$2"
  [[ -d "$dir" ]] || { echo 0; return 0; }
  find "$dir" -type f -name "$pattern" | wc -l | tr -d ' '
}

collect_sql_tables() {
  local tables=""
  for root in looker_files lookml; do
    [[ -d "$root" ]] || continue
    grep -RhoE 'sql_table_name:[[:space:]]*[^;]+' "$root" 2>/dev/null \
      | sed -E 's/sql_table_name:[[:space:]]*//' \
      | sed 's/[[:space:]]*$//' || true
  done | sort -u || true
}

collect_report_warnings() {
  [[ -d out ]] || return 0
  python3 - <<'PY'
import glob, json
seen = set()
for path in sorted(glob.glob('out/*_report.json')):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        for item in data.get('warnings', []):
            if item and item not in seen:
                seen.add(item)
                print(item)
    except Exception:
        pass
PY
}

collect_join_mappings() {
  [[ -d out ]] || return 0
  python3 - <<'PY'
import glob, json
seen = set()
for path in sorted(glob.glob('out/*_report.json')):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        for item in data.get('joins_mapped', []):
            if item and item not in seen:
                seen.add(item)
                print(item)
    except Exception:
        pass
PY
}

license_detected() {
  find . -maxdepth 1 -type f \( -iname 'LICENSE' -o -iname 'LICENSE.txt' -o -iname 'LICENSE.md' \) | head -n 1 || true
}

REPO_TITLE="$(title_case "$PROJECT_BASE_CLEAN")"
WORKFLOW_FILE="$(get_workflow_file)"
WORKFLOW_NAME="$(trim "$(get_workflow_name "$WORKFLOW_FILE")")"
PYTHON_VERSION="$(trim "$(get_workflow_python_version "$WORKFLOW_FILE")")"
NODE_VERSION="$(trim "$(get_workflow_node_version "$WORKFLOW_FILE")")"
LICENSE_FILE="$(license_detected)"

backup_existing_readme

append_line "# $REPO_TITLE"
append_blank
append_line "This repository converts LookML explores and views into Sigma Data Model JSON. It runs locally: no dbt-converter dependency. You get API-ready JSON under \`sigma_model/\` and can optionally push models to Sigma with \`create_model.py\`."
append_blank
append_line "> Generated by \`$(basename "$0")\` on $TIMESTAMP_UTC."

append_section "## What this repo does"
append_line "At a high level:"
append_blank
append_line "1. Store or generate LookML under \`looker_files/<project_name>/\` (sample: \`create_lookml.sh\` creates \`looker_files/plugs/\`; or add your own folder; or import a zip via \`import_lookml.sh\`)."
append_line "2. Run \`setup.sh\` to install dependencies and convert each LookML project under \`looker_files/\` to Sigma JSON via \`tools/build_sigma_explore_json.py\` (uses \`lkml\` and \`pyyaml\` only)."
append_line "3. Outputs go to \`sigma_model/<project_name>/*.json\` (one JSON per LookML model file)."
append_line "4. Optionally run \`create_model.py\` to create data models in Sigma from those JSON files. Push to GitHub is optional and prompted at the end of setup."

append_section "## Repository layout"
append_line '```text'
append_line '.'
for path in \
  .github \
  .github/workflows \
  create_lookml.sh \
  create_model.py \
  import_lookml.sh \
  make_readme.sh \
  setup.sh \
  push_to_git.sh \
  tools \
  looker_files \
  lookml \
  lookml_import \
  out \
  sigma_model \
  requirements.txt; do
  if [[ -e "$path" ]]; then
    append_line "├── $path"
  fi
done
append_line '```'
append_blank
append_line "Key files:"
append_blank
append_line "- \`setup.sh\` — installs dependencies, writes tools and \`.env\`, runs LookML generation and conversion; optional prompts for \`create_model.py\` and push to GitHub."
append_line "- \`create_lookml.sh\` — creates the sample LookML project under \`looker_files/plugs/\` (one model: plugs.model.lkml)."
append_line "- \`import_lookml.sh\` — import LookML from a zip (e.g. \`./import_lookml.sh path/to.zip\` or drop a zip in \`lookml_import/\`)."
append_line "- \`tools/build_sigma_explore_json.py\` — converts LookML to Sigma Data Model JSON (one JSON per explore)."
append_line "- \`create_model.py\` — creates Sigma data models from all JSON files under \`sigma_model/\` (requires \`SIGMA_CLIENT_ID\`, \`SIGMA_CLIENT_SECRET\`)."
append_line "- \`make_readme.sh\` — regenerates this README (run when pushing, or manually)."
append_line "- \`push_to_git.sh\` — optional; commits and pushes (e.g. after running \`make_readme.sh\`)."
if [[ -n "$WORKFLOW_FILE" ]]; then
  append_line "- \`$WORKFLOW_FILE\` — optional CI workflow for conversion on push."
fi

append_section "## Current project contents"
if [[ -d looker_files ]] || [[ -d lookml ]]; then
  append_line "Detected LookML project directories:"
  append_blank
  while IFS= read -r model_dir; do
    [[ -z "$model_dir" ]] && continue
    model_name="$(basename "$model_dir")"
    view_count="$(count_files "$model_dir" '*.view.lkml')"
    model_count="$(count_files "$model_dir" '*.model.lkml')"
    sigma_count="$(count_files "sigma_model/$model_name" '*.json')"
    manifest_present="no"
    report_present="no"
    [[ -f "out/${model_name}_manifest.json" ]] && manifest_present="yes"
    [[ -f "out/${model_name}_report.json" ]] && report_present="yes"

    append_line "- **$model_name**"
    append_line "  - LookML model files: $model_count"
    append_line "  - LookML view files: $view_count"
    append_line "  - Generated Sigma JSON files: $sigma_count"
    append_line "  - Manifest present: $manifest_present"
    append_line "  - Report present: $report_present"
  done < <(collect_lookml_model_dirs)
else
  append_line "No \`looker_files/\` or \`lookml/\` directory was detected."
fi

SQL_TABLES="$(collect_sql_tables || true)"
if [[ -n "$SQL_TABLES" ]]; then
  append_blank
  append_line "Warehouse tables referenced by the current LookML views:"
  append_blank
  while IFS= read -r table_name; do
    [[ -z "$table_name" ]] && continue
    append_line "- \`$(md_escape "$table_name")\`"
  done <<< "$SQL_TABLES"
fi

append_section "## Prerequisites"
append_line "To run locally:"
append_blank
append_line "- Bash, Python 3, pip"
append_line "- Access to your Sigma environment (for \`create_model.py\`)"
append_blank
append_line "Dependencies are in \`requirements.txt\` (pyyaml, lkml, requests). No Node or dbt-converter required for the main LookML → Sigma JSON path."

REQS="$(collect_requirements || true)"
if [[ -n "$REQS" ]]; then
  append_blank
  append_line "Python dependencies currently declared in this repo:"
  append_blank
  while IFS= read -r dep; do
    [[ -z "$dep" ]] && continue
    append_line "- \`$(md_escape "$dep")\`"
  done <<< "$REQS"
fi

append_section "## Setup"
append_line "Run locally:"
append_blank
append_line '```bash'
append_line 'bash setup.sh'
append_line '```'
append_blank
append_line "This installs dependencies, generates sample LookML under \`looker_files/plugs/\` (if \`create_lookml.sh\` is run), converts all \`looker_files/<name>/\` folders to Sigma JSON in \`sigma_model/\`, then optionally runs \`create_model.py\` and/or \`push_to_git.sh\` (Y/N prompts). Review \`.env\` and set real values before pushing to Sigma or GitHub."

append_section "## Configuration"
append_line "The project uses a \`.env\` file. Do **not** commit real secrets."
append_blank
append_line '| Variable | Purpose |'
append_line '|---|---|'
append_line '| `LOOKML_DIR` | Root directory containing LookML model subdirectories (default: \`lookml\`). |'
append_line '| `CONNECTION_ID_DEFAULT` | Default Sigma warehouse connection ID for all models. |'
append_line '| `CONNECTION_ID_<FOLDER>` | Optional: per-project connection (e.g. \`CONNECTION_ID_PLUGS\` for \`looker_files/plugs/\`). Folder name in uppercase, hyphens→underscores. |'
append_line '| `MANIFEST_DATABASE` | Warehouse database name for table paths in generated JSON. |'
append_line '| `MANIFEST_SCHEMA` | Warehouse schema name for table paths. |'
append_line '| `SIGMA_FOLDER_ID` | Sigma folder ID for created data models. |'
append_line '| `API_URL` / `SIGMA_DOMAIN` | Sigma API and domain. |'
append_line '| `API_CLIENT_ID` / `API_SECRET` | Sigma API credentials (for \`create_model.py\`; or use \`SIGMA_CLIENT_ID\` / \`SIGMA_CLIENT_SECRET\`). |'

append_section "## Adding your own LookML"
append_line "- **Folder:** Add a directory \`looker_files/<project_name>/\` with your \`.lkml\` files (views and models). Re-run \`setup.sh\` or \`./regenerate_sigma_json.sh\` to generate Sigma JSON for it."
append_line "- **Zip:** Run \`./import_lookml.sh path/to/your.zip\` or place a zip in \`lookml_import/\` and run \`./import_lookml.sh\`. The zip should contain either one top-level directory with \`.lkml\` files or \`.lkml\` files at the root. Then re-run \`setup.sh\`."

append_section "## Sigma API: relationships"
append_line "Sigma's APIs currently support **many_to_one** relationships only. Joins with \`relationship: one_to_many\` or \`many_to_many\` in LookML are skipped when generating the Sigma payload, and a warning is printed. When Sigma adds support for other relationship types, this behavior can be updated."

if [[ -n "$WORKFLOW_FILE" ]]; then
  append_section "## GitHub Actions (optional)"
  append_line "A workflow file is included. If you push to GitHub, it can run the conversion in CI. Push to GitHub is optional and is prompted at the end of \`setup.sh\`."
fi

append_section "## Generated artifacts"
append_line "After running \`setup.sh\`:"
append_blank
append_line "- \`sigma_model/<model_name>/*.json\` — Sigma Data Model JSON (one per explore), ready for the Sigma API or \`create_model.py\`."
append_line "- \`out/*_report.json\`, \`out/*_manifest.json\` — present only if \`dbtc\` is installed and the optional dbt path is used."

if [[ -d out || -d sigma_model ]]; then
  append_blank
  append_line "Currently detected generated files:"
  append_blank
  [[ -d out ]] && find out -maxdepth 1 -type f | sed 's#^#- `#; s#$#`#' | sort >> "$TMP_FILE" || true
  [[ -d sigma_model ]] && find sigma_model -maxdepth 2 -type f | sed 's#^#- `#; s#$#`#' | sort >> "$TMP_FILE" || true
fi

append_section "## Current caveats and observations"
WARNINGS="$(collect_report_warnings || true)"
JOIN_MAPPINGS="$(collect_join_mappings || true)"

if [[ -n "$WARNINGS" ]]; then
  append_line "The current generated reports include the following notable warnings:"
  append_blank
  while IFS= read -r warning; do
    [[ -z "$warning" ]] && continue
    append_line "- $(md_escape "$warning")"
  done <<< "$WARNINGS"
else
  append_line "No warnings were detected in the current report files."
fi

if [[ -n "$JOIN_MAPPINGS" ]]; then
  append_blank
  append_line "Relationship mappings currently inferred by the patching step:"
  append_blank
  while IFS= read -r mapping; do
    [[ -z "$mapping" ]] && continue
    append_line "- $(md_escape "$mapping")"
  done <<< "$JOIN_MAPPINGS"
fi

append_blank
append_line "Validate connection IDs and folder IDs in \`.env\` before pushing to Sigma. Only \`many_to_one\` joins are sent to the API; others are skipped with a warning."

append_section "## Contributing"
append_line "Contributions are welcome. When making changes, update the LookML sources, rerun generation, and review both \`out/\` reports and \`sigma_model/\` outputs before pushing."

append_section "## License"
if [[ -n "$LICENSE_FILE" ]]; then
  append_line "This repository includes a license file at \`$LICENSE_FILE\`."
else
  append_line "No license file was detected in the repository root. Add one before distributing this project externally."
fi

mv "$TMP_FILE" "$OUTPUT_FILE"
trap - EXIT

echo "README generated at $OUTPUT_FILE"
