# Lookml To Sigma

This repository converts LookML explores and views into Sigma Data Model JSON. It runs locally: no dbt-converter dependency. You get API-ready JSON under `sigma_model/` and can optionally push models to Sigma with `create_model.py`.

> Generated by `make_readme.sh` on 2026-03-13 05:59:09 UTC.

## What this repo does

At a high level:

1. Store or generate LookML under `looker_files/<project_name>/` (sample: `create_lookml.sh` creates `looker_files/plugs/`; or add your own folder; or import a zip via `import_lookml.sh`).
2. Run `setup.sh` to install dependencies and convert each LookML project under `looker_files/` to Sigma JSON via `tools/build_sigma_explore_json.py` (uses `lkml` and `pyyaml` only).
3. Outputs go to `sigma_model/<project_name>/*.json` (one JSON per LookML model file).
4. Optionally run `create_model.py` to create data models in Sigma from those JSON files. Push to GitHub is optional and prompted at the end of setup.

## Repository layout

```text
.
├── .github
├── .github/workflows
├── create_lookml.sh
├── create_model.py
├── import_lookml.sh
├── make_readme.sh
├── setup.sh
├── push_to_git.sh
├── tools
├── looker_files
├── lookml
├── out
├── sigma_model
├── requirements.txt
```

Key files:

- `setup.sh` — installs dependencies, writes tools and `.env`, runs LookML generation and conversion; optional prompts for `create_model.py` and push to GitHub.
- `create_lookml.sh` — creates the sample LookML project under `looker_files/plugs/` (one model: plugs.model.lkml).
- `import_lookml.sh` — import LookML from a zip (e.g. `./import_lookml.sh path/to.zip` or drop a zip in `lookml_import/`).
- `tools/build_sigma_explore_json.py` — converts LookML to Sigma Data Model JSON (one JSON per explore).
- `create_model.py` — creates Sigma data models from all JSON files under `sigma_model/` (requires `SIGMA_CLIENT_ID`, `SIGMA_CLIENT_SECRET`).
- `make_readme.sh` — regenerates this README (run when pushing, or manually).
- `push_to_git.sh` — optional; commits and pushes (e.g. after running `make_readme.sh`).
- `.github/workflows/lookml_to_sigma.yml` — optional CI workflow for conversion on push.

## Current project contents

Detected LookML project directories:

- **looker_bq_qwiklab_ecommerce**
  - LookML model files: 1
  - LookML view files: 8
  - Generated Sigma JSON files: 1
  - Manifest present: no
  - Report present: no
- **plugs**
  - LookML model files: 1
  - LookML view files: 5
  - Generated Sigma JSON files: 1
  - Manifest present: no
  - Report present: no

Warehouse tables referenced by the current LookML views:

- ``cloud-training-demos.looker_ecomm.distribution_centers``
- ``cloud-training-demos.looker_ecomm.events``
- ``cloud-training-demos.looker_ecomm.inventory_items``
- ``cloud-training-demos.looker_ecomm.order_items``
- ``cloud-training-demos.looker_ecomm.products``
- ``cloud-training-demos.looker_ecomm.users``
- `RETAIL.PLUGS_ELECTRONICS.D_CUSTOMER`
- `RETAIL.PLUGS_ELECTRONICS.D_PRODUCT`
- `RETAIL.PLUGS_ELECTRONICS.D_STORE`
- `RETAIL.PLUGS_ELECTRONICS.F_POINT_OF_SALE`
- `RETAIL.PLUGS_ELECTRONICS.F_SALES`

## Prerequisites

To run locally:

- Bash, Python 3, pip
- Access to your Sigma environment (for `create_model.py`)

Dependencies are in `requirements.txt` (pyyaml, lkml, requests). No Node or dbt-converter required for the main LookML → Sigma JSON path.

Python dependencies currently declared in this repo:

- `pyyaml`
- `lkml`
- `requests`

## Setup

Run locally:

```bash
bash setup.sh
```

This installs dependencies, generates sample LookML under `looker_files/plugs/` (if `create_lookml.sh` is run), converts all `looker_files/<name>/` folders to Sigma JSON in `sigma_model/`, then optionally runs `create_model.py` and/or `push_to_git.sh` (Y/N prompts). Review `.env` and set real values before pushing to Sigma or GitHub.

## Configuration

The project uses a `.env` file. Do **not** commit real secrets.

| Variable | Purpose |
|---|---|
| `LOOKML_DIR` | Root directory containing LookML model subdirectories (default: \`lookml\`). |
| `CONNECTION_ID_DEFAULT` | Default Sigma warehouse connection ID for all models. |
| `CONNECTION_ID_<FOLDER>` | Optional: per-project connection (e.g. \`CONNECTION_ID_PLUGS\` for \`looker_files/plugs/\`). Folder name in uppercase, hyphens→underscores. |
| `MANIFEST_DATABASE` | Warehouse database name for table paths in generated JSON. |
| `MANIFEST_SCHEMA` | Warehouse schema name for table paths. |
| `SIGMA_FOLDER_ID` | Sigma folder ID for created data models. |
| `API_URL` / `SIGMA_DOMAIN` | Sigma API and domain. |
| `API_CLIENT_ID` / `API_SECRET` | Sigma API credentials (for \`create_model.py\`; or use \`SIGMA_CLIENT_ID\` / \`SIGMA_CLIENT_SECRET\`). |

## Adding your own LookML

- **Folder:** Add a directory `looker_files/<project_name>/` with your `.lkml` files (views and models). Re-run `setup.sh` or `./regenerate_sigma_json.sh` to generate Sigma JSON for it.
- **Zip:** Run `./import_lookml.sh path/to/your.zip` or place a zip in `lookml_import/` and run `./import_lookml.sh`. The zip should contain either one top-level directory with `.lkml` files or `.lkml` files at the root. Then re-run `setup.sh`.

## Sigma API: relationships

Sigma's APIs currently support **many_to_one** relationships only. Joins with `relationship: one_to_many` or `many_to_many` in LookML are skipped when generating the Sigma payload, and a warning is printed. When Sigma adds support for other relationship types, this behavior can be updated.

## GitHub Actions (optional)

A workflow file is included. If you push to GitHub, it can run the conversion in CI. Push to GitHub is optional and is prompted at the end of `setup.sh`.

## Generated artifacts

After running `setup.sh`:

- `sigma_model/<model_name>/*.json` — Sigma Data Model JSON (one per explore), ready for the Sigma API or `create_model.py`.
- `out/*_report.json`, `out/*_manifest.json` — present only if `dbtc` is installed and the optional dbt path is used.

Currently detected generated files:

- `sigma_model/looker_bq_qwiklab_ecommerce/training_ecommerce_unified_model.json`
- `sigma_model/plugs/plugs_unified_model.json`

## Current caveats and observations

No warnings were detected in the current report files.

Validate connection IDs and folder IDs in `.env` before pushing to Sigma. Only `many_to_one` joins are sent to the API; others are skipped with a warning.

## Contributing

Contributions are welcome. When making changes, update the LookML sources, rerun generation, and review both `out/` reports and `sigma_model/` outputs before pushing.

## License

No license file was detected in the repository root. Add one before distributing this project externally.
